# Generated by Django 3.0.1 on 2020-01-19 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_auto_20200118_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='building',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to='seeker.Building'),
            preserve_default=False,
        ),
    ]
